CREATE TABLE sensor_data
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_of_sensor VARCHAR(255)                            NOT NULL,
    temperature_value  DOUBLE PRECISION                        NOT NULL,
    timestamp          TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_sensor_data PRIMARY KEY (id)
);