CREATE TABLE app_users
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                      VARCHAR(320)                            NOT NULL,
    password_hash              VARCHAR(255)                            NOT NULL,
    preferred_language         VARCHAR(30)                             NOT NULL DEFAULT 'ENGLISH',
    preferred_temperature_unit VARCHAR(30)                             NOT NULL DEFAULT 'CELSIUS',
    preferred_timezone         VARCHAR(64)                             NOT NULL DEFAULT 'UTC',
    enabled                    BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at                 TIMESTAMPTZ                             NOT NULL,
    updated_at                 TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id),
    CONSTRAINT ck_app_users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_app_users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_app_users_preferred_timezone_not_blank CHECK (btrim(preferred_timezone) <> ''),
    CONSTRAINT ck_app_users_preferred_language CHECK (preferred_language IN ('ENGLISH', 'TURKISH')),
    CONSTRAINT ck_app_users_preferred_temperature_unit CHECK (preferred_temperature_unit IN ('CELSIUS', 'FAHRENHEIT', 'KELVIN'))
);

CREATE UNIQUE INDEX uk_app_users_email_lower ON app_users (lower(email));