CREATE TABLE sensors
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id      BIGINT                                  NOT NULL,
    type          VARCHAR(40)                             NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    city          VARCHAR(100)                            NOT NULL,
    district      VARCHAR(100)                            NOT NULL,
    home_location VARCHAR(100)                            NOT NULL,
    time_zone_id      VARCHAR(64)                             NOT NULL,
    active        BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ                             NOT NULL,
    updated_at    TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_sensors PRIMARY KEY (id),
    CONSTRAINT fk_sensors_owner FOREIGN KEY (owner_id) REFERENCES app_users (id),
    CONSTRAINT ck_sensors_type CHECK (type IN ('TEMPERATURE', 'HUMIDITY', 'MOTION')),
    CONSTRAINT ck_sensors_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_sensors_city_not_blank CHECK (btrim(city) <> ''),
    CONSTRAINT ck_sensors_district_not_blank CHECK (btrim(district) <> ''),
    CONSTRAINT ck_sensors_home_location_not_blank CHECK (btrim(home_location) <> ''),
    CONSTRAINT ck_sensors_timezone_not_blank CHECK (btrim(time_zone_id) <> '')
);

CREATE INDEX ix_sensors_owner_id ON sensors (owner_id);
CREATE INDEX ix_sensors_owner_active ON sensors (owner_id, active);
CREATE UNIQUE INDEX uk_sensors_owner_name_lower ON sensors (owner_id, lower(name));