CREATE TABLE sensor_readings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id     BIGINT                                  NOT NULL,
    numeric_value DOUBLE PRECISION,
    boolean_value BOOLEAN,
    unit          VARCHAR(20),
    recorded_at   TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_sensor_readings PRIMARY KEY (id),
    CONSTRAINT fk_sensor_readings_sensor FOREIGN KEY (sensor_id) REFERENCES sensors (id),
    CONSTRAINT ck_sensor_readings_exactly_one_value CHECK (
        (numeric_value IS NOT NULL AND boolean_value IS NULL)
            OR
        (numeric_value IS NULL AND boolean_value IS NOT NULL)
        )
);

CREATE INDEX ix_sensor_readings_sensor_recorded_at
    ON sensor_readings (sensor_id, recorded_at DESC);